### ISSUE TITLE
Error in retrieving 'hitBTC_orderbook'

### ISSUE THREAD

**Issue by pachinkodealer** [ries9112/cryptocurrencyresearch-org#2]
Hi, I just ran this code so far. 

library(pacman)
p_load('pins', 'skimr', 'DT', 'httr', 'jsonlite', # Data Exploration 
       'tidyverse', 'tsibble', 'anytime', # Data Prep
       'ggTimeSeries', 'gifski', 'av', 'magick', 'ggthemes', 'plotly', # Visualization
       'ggpubr', 'ggforce', 'gganimate', 'transformr', # Visualization continued
       'caret', 'doParallel', 'parallel', 'xgboost', # Predictive Modeling
       'brnn', 'party', 'deepnet', 'elasticnet', 'pls',  # Predictive Modeling continued
       'hydroGOF', 'formattable', 'knitr') # Evaluate Model Performance

board_register(name = "pins_board", 
               url = "https://raw.githubusercontent.com/predictcrypto/pins/master/", 
               board = "datatxt")

cryptodata <- pin_get(name = "hitBTC_orderbook")

Then I get an error in my console that says "Error in pin_registry_retrieve(board, name) : 
  Pin 'hitBTC_orderbook' not found in board 'local'."

Is it because my board_register function is not working?

**Comment by pachinkodealer** [comment]
It is saying "7: In p_load("pins", "skimr", "DT", "httr", "jsonlite", "tidyverse",  :
  Failed to install/load:
ggTimeSeries, party, hydroGOF"
When I tried to manually install each, it said those packages were not available for this version of R. Just updated to the latest version.

**Comment by ries9112** [comment]
Thanks for checking it out and sorry about the issues. Were you able to install after updating your version of R?

Could you try the following code and add a screenshot of any error you run into after running this?

```r
# install pins
install.packages('pins')
# register board
board_register(name = "pins_board",
url = "https://raw.githubusercontent.com/predictcrypto/pins/master/",
board = "datatxt")
# pull data
cryptodata <- pin_get(name = "hitBTC_orderbook")
```

**Comment by pachinkodealer** [comment]
[image: image.png]
just tried manually installing. and loading them each with library. "pins",
"skimr", "DT", "httr", "jsonlite", "tidyverse"
I still get this from the p_load.
[image: image.png]
[image: image.png]

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

i'm going to try to load the project in from the repository

**Comment by GitGetGotUp** [comment]
i have pins installed and this popped up:

> # register board
> board_register(name = "pins_board",
+                url = "https://raw.githubusercontent.com/predictcrypto/pins/master/",
+                board = "datatxt")
> # pull data
> cryptodata <- pin_get(name = "hitBTC_orderbook")
Error in pin_registry_retrieve(board, name) : 
  Pin 'hitBTC_orderbook' not found in board 'local'.

**Comment by nih213** [comment]
i have pins installed but still get:

Error in pin_registry_retrieve(board, name) : 
  Pin 'hitBTC_orderbook' not found in board 'local'.

**Comment by ries9112** [comment]
@pachinkodealer I'm sorry I missed this until now. I can't see the images you shared unfortunately. Any luck? The tutorial which [seems to be refreshing fine ](https://github.com/ries9112/cryptocurrencyresearch-org/actions) is running on R 4.0.3, but there are caching mechanisms (with renv) to avoid issues with package installs.

**Comment by ries9112** [comment]
> i have pins installed but still get:
> 
> Error in pin_registry_retrieve(board, name) : Pin 'hitBTC_orderbook' not found in board 'local'.

@GitGetGotUp could you show the output of the following code:
```r
board_register(name = "pins_board",
               url = "https://raw.githubusercontent.com/predictcrypto/pins/master/",
               board = "datatxt")
```
Working on my end:
![image](https://user-images.githubusercontent.com/32306488/147072116-2590126a-1742-4d46-952c-e01aac0668d1.png)

**Comment by pachinkodealer** [comment]
cryptodata <- pin_get(board = "pins_board", name = "hitBTC_orderbook")

![image](https://user-images.githubusercontent.com/75056795/147947085-d787f8be-3117-4f83-a0aa-c7bb007a1109.png)

Figured it out, it needs the "board" , pins_board specifically.
